/*
 * JSMin
 * Javascript Compressor
 * http://www.crockford.com/
 * http://www.smallsharptools.com/Projects/Packer/
*/

// RangeHelper.js

if(typeof Narmand==="undefined"){Narmand={};}
$.extend(true,Narmand,{RangeHelper:{ToggleRangeSurroundingByTag:function(Range,TagName){if(this.DoesRangeContainTag(Range,TagName)){this.CleanRangeByTag(Range,TagName);return;}
var TagElement=document.createElement(TagName);this.SurroundRangeByElement(Range,TagElement);},SurroundRangeByElement:function(Range,Element){if(Range.canSurroundContents()){Range.surroundContents(Element);}},DoesRangeContainTag:function(Range,TagName){TagName=TagName.toLowerCase();var NodeIterator=Range.createNodeIterator();while(NodeIterator.hasNext()){var CurrentNode=NodeIterator.next();if(CurrentNode.nodeType===3&&CurrentNode.parentNode.tagName.toLowerCase()===TagName){return true;}
if(CurrentNode.nodeType===1&&CurrentNode.tagName.toLowerCase()===TagName){return true;}}
return false;},GetTagElementSurroundingRangeByTagName:function(Range,TagName){TagName=TagName.toLowerCase();var NodeIterator=Range.createNodeIterator();while(NodeIterator.hasNext()){var CurrentNode=NodeIterator.next();if(CurrentNode.nodeType===3&&CurrentNode.parentNode.tagName.toLowerCase()===TagName){return CurrentNode;}
if(CurrentNode.nodeType===1&&CurrentNode.tagName.toLowerCase()===TagName){return CurrentNode;}}
return null;},CleanRangeByTag:function(Range,TagName){TagName=TagName.toLowerCase();var NodeIterator=Range.createNodeIterator();while(NodeIterator.hasNext()){var CurrentNode=NodeIterator.next();if(CurrentNode.nodeType===3&&CurrentNode.parentNode.tagName.toLowerCase()===TagName){$(CurrentNode).unwrap();}
if(CurrentNode.nodeType===1&&CurrentNode.tagName.toLowerCase()===TagName){$(CurrentNode).contents().unwrap();}}
Range.commonAncestorContainer.normalize();}}});
// SanitizationHelper.js

if(typeof Narmand==="undefined"){Narmand={};}
$.extend(true,Narmand,{SanitizationHelper:{count:0,SanitizeElementContents:function(Element,WhiteList){WhiteList=this.NormalizeWhiteList(WhiteList);while(this.HasElementAnyBlackListedContent(Element,WhiteList)){var ElementNodes=this.GetElementNodesContentsOfElement(Element);this.count++;if(this.count>100){break;}
var CurrentElement=ElementNodes[0];while(CurrentElement!==undefined){var NextElement=$(CurrentElement).next()[0];this.SanitizeElementContent(CurrentElement,WhiteList);CurrentElement=NextElement;}}},NormalizeWhiteList:function(WhiteList){if(WhiteList===undefined){return"";}
if(WhiteList[0]!==" "){WhiteList=" "+WhiteList;}
if(WhiteList[WhiteList.length-1]!==" "){WhiteList=WhiteList+" ";}
return WhiteList.toLowerCase();},GetElementNodesContentsOfElement:function(Element){var ElementNodes=[];var Contents=$(Element).contents();for(var i=0;i<Contents.length;i++){switch(Contents[i].nodeType){case 1:ElementNodes.push(Contents[i]);break;case 8:this.ClearCommentNode(Contents[i]);break;}}
return ElementNodes;},ClearCommentNode:function(CommentNode){$(CommentNode).remove();},HasElementAnyBlackListedContent:function(Element,WhiteList){var ElementNodes=this.GetElementNodesContentsOfElement(Element);for(var i=0;i<ElementNodes.length;i++){ElementNodeTagName=ElementNodes[i].tagName;if(!this.IsTagNameWhiteListed(ElementNodeTagName,WhiteList)){return true;}
if(this.HasTagAnyBlackListedAttribute(ElementNodes[i],WhiteList)){return true;}}
return false;},HasTagAnyBlackListedAttribute:function(ElementContent,WhiteList){ElementContentTagName=ElementContent.tagName;var ElementAttributes=this.GetElementAttributes(ElementContent);for(var i=0;i<ElementAttributes.length;i++){if(!this.IsTagAttributeWhiteListed(ElementContentTagName,ElementAttributes[i],WhiteList)){return true;}}
return false;},SanitizeElementContent:function(ElementContent,WhiteList){ElementContentTagName=ElementContent.tagName;if(!this.IsTagNameWhiteListed(ElementContentTagName,WhiteList)){var TagContents=$(ElementContent).contents();if(TagContents.length>0){TagContents.fixedUnwrap();}
else{$(ElementContent).remove();}
return;}
this.SanitizeElementAttributes(ElementContent,WhiteList);try{$(ElementContent).text($(ElementContent).text());}
catch(e){}},IsTagNameWhiteListed:function(TagName,WhiteList){TagName=TagName.toLowerCase();if(WhiteList.indexOf(" "+TagName+" ")>-1){return true;}
return false;},SanitizeElementAttributes:function(ElementContent,WhiteList){ElementContentTagName=ElementContent.tagName;var ElementAttributes=this.GetElementAttributes(ElementContent);for(var i=0;i<ElementAttributes.length;i++){if(!this.IsTagAttributeWhiteListed(ElementContentTagName,ElementAttributes[i],WhiteList)){$(ElementContent).removeAttr(ElementAttributes[i]);}}},GetElementAttributes:function(ElementContent){var ElementAttributeNames=[];var ElementAttributes=ElementContent.attributes;for(var i=0;i<ElementAttributes.length;i++){ElementAttributeNames.push(ElementAttributes.item(i).nodeName);}
return ElementAttributeNames;},IsTagAttributeWhiteListed:function(TagName,TagAttribute,WhiteList){TagName=TagName.toLowerCase();TagAttribute=TagAttribute.toLowerCase();if(TagAttribute==="shape"){return true;}
if(WhiteList.indexOf(" "+TagName+"["+TagAttribute+"] ")>-1){return true;}
return false;}}});$.fn.fixedUnwrap=function(){this.parent(':not(body)').each(function(){$(this).replaceWith(this.childNodes);});return this;};
// NeatEditor.js

if(typeof Narmand==="undefined"){Narmand={};}
$.extend(true,Narmand,{NeatEditor:{_LastEditorID:0,Init:function(Options){$.extend(true,this.Options,Options);this.ConstructEditorElemets();},Options:{Container:null,Direction:"ltr",AutoSyncTextareaWithEditor:true},ConstructEditorElemets:function(){this._LastEditorID++;var EditorWrapper=null;if(this.HasTextareaAssociatedEditorWrapper()){EditorWrapper=this.GetAssociatedEditorWrapperOfTextarea();EditorWrapper.empty();}
else{this.Options.Container.data("NarmandNeatEditorID",this._LastEditorID);EditorWrapper=$("<div>").addClass("NarmandNeatEditor").attr("id","NarmandNeatEditor_"+this._LastEditorID).data("Options",this.Options);}
if(this.Options.Direction==="rtl"){EditorWrapper.addClass("NarmandNeatEditorRightToLeft");}
else{EditorWrapper.removeClass("NarmandNeatEditorRightToLeft");}
var Sections=$("<div>").addClass("Sections").appendTo(EditorWrapper);var SectionAdders=$("<div>").addClass("SectionAdders").appendTo(EditorWrapper);$("<div>").addClass("Tag").text("+").appendTo(SectionAdders);Sections.append(SectionAdders);for(var ProviderName in this.SectionProviders){var Provider=Narmand.NeatEditor.SectionProviders[ProviderName];var AdderButtonBase=this.CreateAdderButtonBase(ProviderName);SectionAdders.append(Provider.CreateAdderButton(AdderButtonBase));}
SectionAdders.find(".SectionAdder").click(function(){Narmand.NeatEditor.TrySyncingTextareaWithEditor($(this));});this.ParseHtmlToEditor(this.Options.Container.val(),EditorWrapper);this.Options.Container.after(EditorWrapper);this.SectionProvidersHelper.MakeSectionsSortable();},HasTextareaAssociatedEditorWrapper:function(){if(this.Options.Container.data("NarmandNeatEditorID")!==undefined){return true;}
return false;},GetAssociatedEditorWrapperOfTextarea:function(){var TextareaNeatEditorID=this.Options.Container.data("NarmandNeatEditorID");if(TextareaNeatEditorID!==undefined){return $("#NarmandNeatEditor_"+TextareaNeatEditorID);}
else{throw"There is no editor associated with this textarea";}},CreateAdderButtonBase:function(SectionProviderName){var AdderButtonBase=$("<a>").addClass("SectionAdder").addClass(SectionProviderName).text("+ "+SectionProviderName);return AdderButtonBase;},RelocateSectionAdderBelowSection:function(SectionElement){if(!SectionElement.next().is(".SectionAdders")){var EditorWrapper=SectionElement.closest(".NarmandNeatEditor")
var SectionAdders=EditorWrapper.find(".SectionAdders");EditorHeight=EditorWrapper.height();EditorWrapper.height(EditorWrapper.height());SectionAdders.children().hide();SectionAdders.slideUp("fast",function(){SectionElement.after(SectionAdders);SectionAdders.slideDown("fast",function(){SectionAdders.children().fadeIn("fast");EditorWrapper.css("height","auto");});});}},ParseHtmlToEditor:function(HtmlCode,EditorWrapper){var RootElementsWrapper=$("<div>").html(HtmlCode);while(RootElementsWrapper.children()[0]!=undefined){var NextRootElement=RootElementsWrapper.children()[0];var TagName=NextRootElement.nodeName;var SectionProvider=Narmand.NeatEditor.GetSectionProviderByTagName(TagName);if(typeof SectionProvider.ExtractAnyDefinedTagsFromSection!=="undefined"){SectionProvider.ExtractAnyDefinedTagsFromSection($(NextRootElement));}
SectionProvider.AddSectionToEditor($(NextRootElement),EditorWrapper);$(NextRootElement).remove();}
this.TrySyncingTextareaWithEditor(EditorWrapper.children(":first"));},TrySyncingTextareaWithEditor:function(EditorInsideElement){var NarmandEditor=EditorInsideElement.closest(".NarmandNeatEditor");var Options=NarmandEditor.data("Options");if(Options.AutoSyncTextareaWithEditor){this.SyncTextareaWithEditor(NarmandEditor);}},SyncTextareaWithEditor:function(EditorWrapper){var HtmlCode="";$(EditorWrapper).find(".Sections .Section").each(function(){var SectionProviderName=$(this).data("SectionProviderName");HtmlCode+=Narmand.NeatEditor.SectionProviders[SectionProviderName].ExportSectionHtml($(this))+"\r\n";});EditorWrapper.data("Options").Container.val(HtmlCode);},SectionProviders:{},SectionProvidersHelper:{CreateSectionElement:function(SectionProviderName){var SectionToolsWrapper=$("<div>").addClass("ToolsWrapper");$("<div>").addClass("CloseButton").text("x").click(function(){var SectionsWrapper=$(this).closest(".Sections");$(this).closest(".Section").remove();Narmand.NeatEditor.TrySyncingTextareaWithEditor(SectionsWrapper);return false;}).appendTo(SectionToolsWrapper);$("<div>").addClass("Handle").text("::").appendTo(SectionToolsWrapper);var Content=$("<div>").addClass("Content");var SectionTag=$("<div>").addClass("Tag").text(SectionProviderName);return $("<div>").addClass("Section").data("SectionProviderName",SectionProviderName).append(SectionToolsWrapper).append(Content).append(SectionTag).focusin(function(Event){if($(Event.target).is("a.Tool")){return false;}
Narmand.NeatEditor.RelocateSectionAdderBelowSection($(this));Narmand.NeatEditor.Toolbar.CreateToolbarForSection($(this));}).keyup(function(){Narmand.NeatEditor.TrySyncingTextareaWithEditor($(this));});},MakeSectionsSortable:function(){$(".Sections").sortable({handle:'.ToolsWrapper .Handle',forcePlaceholderSize:true,containment:'parent',over:function(){Narmand.NeatEditor.Toolbar.Hide();},stop:function(event,ui){Narmand.NeatEditor.TrySyncingTextareaWithEditor(ui.item);},axis:'y'});}},Extend:function(Section){$.extend(true,Narmand.NeatEditor.SectionProviders,Section);},GetSectionProviderByTagName:function(TagName){TagName=TagName.toLowerCase();for(var ProviderName in this.SectionProviders){var Provider=this.SectionProviders[ProviderName];if(Provider.TagName===TagName){return Provider;}}
return Narmand.NeatEditor.SectionProviders.HtmlCode},Toolbar:{CreateToolbarForSection:function(SectionElement){var EditorWrapper=SectionElement.closest(".NarmandNeatEditor");var EditorToolbar=this.CunstructToolbarElementIfNotExists(EditorWrapper);var SectionProviderName=SectionElement.data("SectionProviderName");var Provider=Narmand.NeatEditor.SectionProviders[SectionProviderName];this.AppendProviderToolsToEditorToolbar(Provider,EditorToolbar);this.PositionToolbarAccordingToSection(EditorToolbar,SectionElement);},CunstructToolbarElementIfNotExists:function(EditorWrapper){var EditorToolbar=EditorWrapper.find(".Toolbar:first");if(EditorToolbar.length===0){EditorToolbar=$("<div>").addClass("Toolbar").appendTo(EditorWrapper);}
return EditorToolbar.empty();},AppendProviderToolsToEditorToolbar:function(Provider,EditorToolbar){if(Provider.Tools===undefined){return;}
for(var ProviderToolName in Provider.Tools){$("<a>").addClass("Tool").addClass(ProviderToolName).data("ToolName",ProviderToolName).data("SectionProvider",Provider).attr("title",Provider.Tools[ProviderToolName].Title).attr("href","").click(function(Event){try{Narmand.NeatEditor.Toolbar.ToolSelected($(this));}
catch(e){console.info(e);}
return false;}).appendTo(EditorToolbar);}},PositionToolbarAccordingToSection:function(ToolbarElement,SectionElement){if(ToolbarElement.children().length===0){ToolbarElement.hide();return;}
SectionElement.append(ToolbarElement);ToolbarElement.show();},Hide:function(){$(".NarmandNeatEditor .Toolbar").hide();},ToolSelected:function(ToolElement){var ToolsWrapperElement=ToolElement.parent();var ToolName=ToolElement.data("ToolName");var SectionProvider=ToolElement.data("SectionProvider");SectionProvider.Tools[ToolName].Act();Narmand.NeatEditor.TrySyncingTextareaWithEditor(ToolsWrapperElement);}}}});Narmand.NeatEditor.Extend({HtmlCode:{CreateAdderButton:function(AdderButtonBase){AdderButtonBase.click(function(){var EditorWrapper=$(this).closest(".NarmandNeatEditor");Narmand.NeatEditor.SectionProviders.HtmlCode.AddSectionToEditor($("<code>replace with your html code</code>"),EditorWrapper);return false;}).text("+ HTML Code");return AdderButtonBase;},AddSectionToEditor:function(Content,EditorWrapper){var SectionsWrapper=EditorWrapper.find(".Sections");var HtmlCode=$("<div>").append(Content).html();if(this._IsLastSectionHtmlCode(SectionsWrapper)){var LastHtmlCodeTextarea=SectionsWrapper.find(".Section:last textarea");LastHtmlCodeTextarea.val(LastHtmlCodeTextarea.val()+"\r\n"+HtmlCode);return;}
var HtmlCodeSection=Narmand.NeatEditor.SectionProvidersHelper.CreateSectionElement("HtmlCode");HtmlCodeSection.addClass("HtmlCode");var EditableSection=$("<textarea>").val(HtmlCode).css("width","100%").appendTo(HtmlCodeSection.find(".Content"));EditorWrapper.find(".SectionAdders").before(HtmlCodeSection);},_IsLastSectionHtmlCode:function(SectionsWrapper){var SectionBeforeSectionAddersElement=SectionsWrapper.find(".SectionAdders").prev();if(SectionBeforeSectionAddersElement.length===0){return false;}
var SectionProviderName=SectionBeforeSectionAddersElement.data("SectionProviderName");if(SectionProviderName==="HtmlCode"){return true;}
return false;},TagName:null,ExportSectionHtml:function(SectionElement){var EncodedHtml=SectionElement.find(".Content > textarea").val();return this._HtmlDecode(EncodedHtml);},_HtmlDecode:function(HtmlToDecode){return HtmlToDecode.replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>');},_HtmlEncode:function(HtmlToEncode){return HtmlToEncode.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');}}});$.fn.extend({NeatEditor:function(Options){if(Options===undefined){var Options={};}
return this.each(function(){Options.Container=$(this);Narmand.NeatEditor.Init(Options);});}});
// NeatEditor.SectionProviders.Pragraph.js

Narmand.NeatEditor.Extend({Paragraph:{CreateAdderButton:function(AdderButtonBase){AdderButtonBase.click(function(){var EditorWrapper=$(this).closest(".NarmandNeatEditor");Narmand.NeatEditor.SectionProviders.Paragraph.AddSectionToEditor($("<p>Replace this with you text</p>"),EditorWrapper);return false;}).text("+ Paragraph");return AdderButtonBase;},ExtractAnyDefinedTagsFromSection:function(RootElement){RootElement.find("img").insertBefore(RootElement);},AddSectionToEditor:function(Section,EditorWrapper){this.Sanitization.Sanitize(Section);var SectionsWrapper=EditorWrapper.find(".Sections");var ParagraphSection=Narmand.NeatEditor.SectionProvidersHelper.CreateSectionElement("Paragraph");ParagraphSection.addClass("Paragraph");var EditableSection=$("<div>").html(Section.html()).attr("contentEditable",true).bind("paste",function(){Narmand.NeatEditor.SectionProviders.Paragraph.Sanitization.SanitizeWithDelay($(this));}).appendTo(ParagraphSection.find(".Content"));if(Section.attr("dir")!==undefined){EditableSection.attr("dir",Section.attr("dir"));}
EditorWrapper.find(".SectionAdders").before(ParagraphSection);},TagName:"p",Tools:{MakeStrong:{Title:"Make selection strong",Act:function(){var Selection=rangy.getSelection();var Range=Selection.getAllRanges()[0];if(!Narmand.NeatEditor.SectionProviders.Paragraph._CanToolActOnRange(Range)){return;}
Narmand.RangeHelper.ToggleRangeSurroundingByTag(Range,"strong");Selection.removeAllRanges();}},Emphasize:{Title:"Emphasize on selection",Act:function(){var Selection=rangy.getSelection();var Range=Selection.getAllRanges()[0];if(!Narmand.NeatEditor.SectionProviders.Paragraph._CanToolActOnRange(Range)){return;}
Narmand.RangeHelper.ToggleRangeSurroundingByTag(Range,"em");Selection.removeAllRanges();}},Strikethrough:{Title:"Strike selection out",Act:function(){var Selection=rangy.getSelection();var Range=Selection.getAllRanges()[0];if(!Narmand.NeatEditor.SectionProviders.Paragraph._CanToolActOnRange(Range)){return;}
Narmand.RangeHelper.ToggleRangeSurroundingByTag(Range,"del");Selection.removeAllRanges();}},CreateLink:{Title:"Create or modify link",PromptMessage:"Please link target URL",Act:function(){var Selection=rangy.getSelection();var Range=Selection.getAllRanges()[0];if(!Narmand.NeatEditor.SectionProviders.Paragraph._CanToolActOnRange(Range)){return;}
if(Narmand.RangeHelper.DoesRangeContainTag(Range,"a")){this.ModifyExistingLink(Range);return;}
var AnchorHref=prompt(this.PromptMessage,"http://");if(AnchorHref===null||AnchorHref===""){return;}
var AnchorElement=$("<a>").attr("href",AnchorHref)[0];Narmand.RangeHelper.SurroundRangeByElement(Range,AnchorElement);Selection.removeAllRanges();},ModifyExistingLink:function(Range){SurroundingAnchor=Narmand.RangeHelper.GetTagElementSurroundingRangeByTagName(Range,"a");AnchorHref=$(SurroundingAnchor).attr("href");var AnchorHref=prompt(this.PromptMessage,AnchorHref);if(AnchorHref===null){return;}
AnchorHref=AnchorHref.trim();if(AnchorHref!==""){$(SurroundingAnchor).attr("href",AnchorHref);}
else{Narmand.RangeHelper.CleanRangeByTag(Range,"a");}}},ClearFormatting:{Title:"Clear selection formatting",Act:function(){var Selection=rangy.getSelection();var Range=Selection.getAllRanges()[0];if(!Narmand.NeatEditor.SectionProviders.Paragraph._CanToolActOnRange(Range)){return;}
Narmand.NeatEditor.SectionProviders.Paragraph._ClearFormattingInRange(Range);Selection.removeAllRanges();}},ChanegeDirectionToLeftToRight:{Title:"Change paragraph direction left to right",Act:function(){var Selection=rangy.getSelection();var Range=Selection.getAllRanges()[0];var ParentElement=$(Range.commonAncestorContainer);var ParagraphSelector=".NarmandNeatEditor .Section .Content > div";if(ParentElement.is(ParagraphSelector)){ParentElement.css("direction","ltr");}
else{ParentElement.closest(ParagraphSelector).attr("dir","ltr");}}},ChanegeDirectionToRightToLeft:{Title:"Change paragraph direction right to left",Act:function(){var Selection=rangy.getSelection();var Range=Selection.getAllRanges()[0];var ParentElement=$(Range.commonAncestorContainer);var ParagraphSelector=".NarmandNeatEditor .Section .Content > div";if(ParentElement.is(ParagraphSelector)){ParentElement.css("direction","rtl");}
else{ParentElement.closest(ParagraphSelector).attr("dir","rtl");}}}},Sanitization:{WhiteList:"strong em del a a[href] a[target] br",Sanitize:function(Element){Narmand.SanitizationHelper.SanitizeElementContents(Element,this.WhiteList);},SanitizeWithDelay:function(Element){setTimeout(function(){var WhiteList=Narmand.NeatEditor.SectionProviders.Paragraph.Sanitization.WhiteList;Narmand.SanitizationHelper.SanitizeElementContents(Element,WhiteList);Narmand.NeatEditor.TrySyncingTextareaWithEditor(Element);},100);}},_CanToolActOnRange:function(Range){var ParentElement=$(Range.commonAncestorContainer);var ParagraphSelector=".NarmandNeatEditor .Section .Content > div";if(ParentElement.is(ParagraphSelector)){return true;}
if(ParentElement.closest(ParagraphSelector).length>0){return true;}
return false;},_ClearFormattingInRange:function(Range){var NodeIterator=Range.createNodeIterator();while(NodeIterator.hasNext()){var CurrentNode=NodeIterator.next();if(CurrentNode.nodeType===3&&CurrentNode.parentNode.tagName.toLowerCase()!=="div"){$(CurrentNode).unwrap();}}
Range.commonAncestorContainer.normalize();},ExportSectionHtml:function(SectionElement){var ParagraphTag=SectionElement.find(".Content > div");var DirectionAttribute=(ParagraphTag.attr("dir")!==undefined)?" dir='"+ParagraphTag.attr("dir")+"'":"";return"<p"+DirectionAttribute+">"+ParagraphTag.html()+"</p>";}}});
// NeatEditor.SectionProviders.Heading.js

Narmand.NeatEditor.Extend({Heading:{CreateAdderButton:function(AdderButtonBase){AdderButtonBase.click(function(){var EditorWrapper=$(this).closest(".NarmandNeatEditor");Narmand.NeatEditor.SectionProviders.Heading.AddSectionToEditor($("<span>Replace with your heading</span>"),EditorWrapper);return false;}).text("+ Heading");return AdderButtonBase;},AddSectionToEditor:function(Content,EditorWrapper){var SectionsWrapper=EditorWrapper.find(".Sections");var HeadingText=$("<div>").append(Content).text();var HeadingSection=Narmand.NeatEditor.SectionProvidersHelper.CreateSectionElement("Heading");HeadingSection.addClass("Heading");var EditableSection=$("<input type='text'>").val(HeadingText).keydown(function(Event){if(Event.which===13){return false;}}).css("width","100%").appendTo(HeadingSection.find(".Content"));EditorWrapper.find(".SectionAdders").before(HeadingSection);},TagName:"h2",ExportSectionHtml:function(SectionElement){var EncodedHeadingValue=this._HtmlEncode(SectionElement.find(".Content > input").val());return"<h2>"+EncodedHeadingValue+"</h2>";},_HtmlEncode:function(HtmlToEncode){return HtmlToEncode.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');}}});
// NeatEditor.SectionProviders.Image.js

Narmand.NeatEditor.Extend({Image:{CreateAdderButton:function(AdderButtonBase){AdderButtonBase.click(function(){var EditorWrapper=$(this).closest(".NarmandNeatEditor");Narmand.NeatEditor.SectionProviders.Image.AddSectionToEditor($("<img src='' alt=''/>"),EditorWrapper);return false;}).text("+ Image");return AdderButtonBase;},AddSectionToEditor:function(Content,EditorWrapper){var SectionsWrapper=EditorWrapper.find(".Sections");var ImageElement=$("<div>").append(Content);var ImageUrl=ImageElement.find("img").attr("src");var ImageAlternativeText=ImageElement.find("img").attr("alt");var ImageSection=Narmand.NeatEditor.SectionProvidersHelper.CreateSectionElement("Image");ImageSection.addClass("Image");var ConfigSection=$("<div>").html(this._SectionTemplate);ConfigSection.find("input").keydown(function(Event){if(Event.which===13){return false;}});ConfigSection.find("input.Url").val(ImageUrl);ConfigSection.find("input.Description").val(ImageAlternativeText);ConfigSection.appendTo(ImageSection.find(".Content"));EditorWrapper.find(".SectionAdders").before(ImageSection);},TagName:"img",ExportSectionHtml:function(SectionElement){var ImageUrl=SectionElement.find("input.Url").val();ImageUrl=this._HtmlEncode(ImageUrl);var AlternativeText=SectionElement.find("input.Description").val();AlternativeText=(AlternativeText==="")?'':' alt="'+AlternativeText+'" ';AlternativeText=jQuery.trim(this._HtmlEncode(AlternativeText));return'<img src="'+ImageUrl+'"'+AlternativeText+'/>';},_SectionTemplate:"<label>Url:</label><input type='text' class='Url'/><br/>"+"<label>Description:</label><input type='text' class='Description' />",_HtmlEncode:function(HtmlToEncode){return HtmlToEncode.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');}}});
